### ISSUE TITLE
Error during sync from Gitlab connector: Found multiple possible origins from catalog

### ISSUE THREAD

**Issue by batjko** [faros-ai/faros-community-edition#228]
**Describe the bug**
Unable to sync from Gitlab to Faros destination.

After setting up Faros CE locally, starting it all up using `./start.sh`, I set up a Source (Gitlab) and Destination (Faros, which I assume is the safest to start with, just to try things out).
This appeared to have been successful.

But when I try to sync in Airbyte, it keeps throwing me this error: `Encountered an error while writing to destination: VError: Found multiple possible origins from catalog`

Log entry:
```shell
2022-10-18 20:15:41 [43mdestination[0m > Encountered an error while writing to destination: VError: Found multiple possible origins from catalog: branches,commits,epic_issues,epics,group_issue_boards,group_labels,group_members,group_milestones,groups,issues,jobs,merge_request_commits,merge_requests,pipelines,pipelines_extended,project_labels,project_members,project_milestones,projects,releases,tags,users - {"jse_shortmsg":"Found multiple possible origins from catalog: branches,commits,epic_issues,epics,group_issue_boards,group_labels,group_members,group_milestones,groups,issues,jobs,merge_request_commits,merge_requests,pipelines,pipelines_extended,project_labels,project_members,project_milestones,projects,releases,tags,users","jse_info":{},"message":"Found multiple possible origins from catalog: branches,commits,epic_issues,epics,group_issue_boards,group_labels,group_members,group_milestones,groups,issues,jobs,merge_request_commits,merge_requests,pipelines,pipelines_extended,project_labels,project_members,project_milestones,projects,releases,tags,users"}
2022-10-18 20:15:41 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$getDestinationOutputRunnable$7):415 - State in DefaultReplicationWorker from destination: io.airbyte.protocol.models.AirbyteMessage@35819db0[type=TRACE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=<null>,trace=io.airbyte.protocol.models.AirbyteTraceMessage@3b466570[type=ERROR,emittedAt=1.666124141733E12,error=io.airbyte.protocol.models.AirbyteErrorTraceMessage@3f79f6c0[message=Found multiple possible origins from catalog: branches,commits,epic_issues,epics,group_issue_boards,group_labels,group_members,group_milestones,groups,issues,jobs,merge_request_commits,merge_requests,pipelines,pipelines_extended,project_labels,project_members,project_milestones,projects,releases,tags,users,internalMessage=VError,stackTrace=VError: Found multiple possible origins from catalog: branches,commits,epic_issues,epics,group_issue_boards,group_labels,group_members,group_milestones,groups,issues,jobs,merge_request_commits,merge_requests,pipelines,pipelines_extended,project_labels,project_members,project_milestones,projects,releases,tags,users
    at FarosDestination.getOrigin (/home/node/airbyte/destinations/airbyte-faros-destination/lib/destination.js:269:19)
    at FarosDestination.write (/home/node/airbyte/destinations/airbyte-faros-destination/lib/destination.js:277:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Command.<anonymous> (/home/node/airbyte/faros-airbyte-cdk/lib/destinations/destination-runner.js:67:34)
    at async Command.parseAsync (/home/node/airbyte/node_modules/commander/lib/command.js:917:5),failureType=system_error,additionalProperties={jse_shortmsg=Found multiple possible origins from catalog: branches,commits,epic_issues,epics,group_issue_boards,group_labels,group_members,group_milestones,groups,issues,jobs,merge_request_commits,merge_requests,pipelines,pipelines_extended,project_labels,project_members,project_milestones,projects,releases,tags,users, jse_info={}}],additionalProperties={}],additionalProperties={}]
2022-10-18 20:15:41 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(run):180 - Sync worker failed.
```

In the destination's replication settings, all streams are all enabled (was by default, I didn't change anything):

![image](https://user-images.githubusercontent.com/7287076/196536338-919d2408-aea4-474f-828c-b9d6a5973b06.png)

**To Reproduce**
1. As per Quickstart, I cloned the repo and ran `./start.sh`
2. Set up Gitlab source (self-hosted, v15.4.1) in Airbyte 
3. Select Faros Destination for the connection.
4. Navigate to Connection and try to sync.
5. See error and be sad.

![image](https://user-images.githubusercontent.com/7287076/196537469-bfe70578-cb03-4336-9669-aeeda680f407.png)

**Expected behavior**
Successful sync, so I can see my data in a Metabase dashboard.

**Deployment**
* local, docker on Linux (WSL2), as per Quickstart

**Comment by thomas-gerber** [comment]
@batjko you are missing the [table prefix](https://community.faros.ai/docs/gitlab-source#connection-settings) setting.

Note that Faros CE should already have a canned connections at startup between GitLab and Faros. Take a look, it is already configured properly: [link](http://localhost:8000/workspaces/b740a9b4-048b-4500-b41b-038e14a3f2d5/connections/cef1b90d-ab16-4645-a0e3-b81818b8ffc7/replication).

**Comment by batjko** [comment]
> you are missing the [table prefix](https://community.faros.ai/docs/gitlab-source#connection-settings) setting.

Ah interesting, that was not obvious in the UI, as the field is optional. I'll try that.

> Note that Faros CE should already have a canned connections at startup between GitLab and Faros. Take a look, it is already configured properly: [link](http://localhost:8000/workspaces/b740a9b4-048b-4500-b41b-038e14a3f2d5/connections/cef1b90d-ab16-4645-a0e3-b81818b8ffc7/replication).

I did not see this. I kinda didn't learn how Airbyte works, and the UI was very confusing, I have to say. So I just followed the quickstart.

Thanks for your help, @thomas-gerber .
