### ISSUE TITLE
Sync worker failed

### ISSUE THREAD

**Issue by suzuki-reha** [faros-ai/faros-community-edition#289]
**Describe the bug**

- Airbyte version: example is .39.37-alpha
- OS Version / Ubuntu 20.04
- Deployment: Docker
- Source Connector and version: Github(cloud)
- Destination Connector and version: Faros Destination
- Step where error happened: Sync job

- After adding Github to the Source item, I get a "Sync worker failed" error when I run Sync now.

```sh
`2023-03-08 01:16:11 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(run):180 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.general.DefaultReplicationWorker$DestinationException: Destination process exited with non-zero exit code 1
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:175) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Destination process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:119) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:137) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:65) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:158) ~[io.airbyte-airbyte-workers-0.39.37-alpha.jar:?]
		at java.lang.Thread.run(Thread.java:833) [?:?]`
```

**Logs**
[server-logs.txt](https://github.com/faros-ai/faros-community-edition/files/10927917/server-logs.txt)
[logs-5.txt](https://github.com/faros-ai/faros-community-edition/files/10927926/logs-5.txt)

**Expected behavior**
clear and concise description of what you expected to happen.

**Screenshots and logs**
If applicable, add screenshots and logs to help explain your problem.

**Deployment**
* If local, docker and OS versions
* If cloud, cluster type and version

**Comment by thomas-gerber** [comment]
According to the worker log, this seems to try to write from a source I do not recognize (`airbyte/source-all-types:dev`) to snowflake, which is not how Faros CE is set up..
Do you have the full log of the failed sync?

**Comment by suzuki-reha** [comment]
How about this log? It was executed just now.

- Airbyte Version: 0.39.37-alpha
- Source: GitHub (0.4.2)
- Destination: Faros Destination (0.4.69)

[logs-64.txt](https://github.com/faros-ai/faros-community-edition/files/10943879/logs-64.txt)

**Comment by thomas-gerber** [comment]
You are probably missing the table prefix.
In the connection page, go to Replication, and look for `Stream Prefix`; it should contain `github_source__github__`

See https://community.faros.ai/docs/github-source#connection-settings and https://community.faros.ai/docs/faros-destination#table-prefix.

I am curious, did you create the source, destination and connection? Those should have been auto-provisioned at startup, here: http://localhost:8000/workspaces/b740a9b4-048b-4500-b41b-038e14a3f2d5/connections/6421df4e-0c5a-4666-a530-9c01de683518/status

**Comment by suzuki-reha** [comment]
I put a value in `Stream Prefix`: as you suggested and the synchronization between Github and DB was successful.
 I appreciate your dedication and support. 

Thank you very much.
